name: 'Cache install Nix packages'
description: 'Use the GitHub Actions cache for Nix packages'
author: 'Rik Huijzer'
inputs:
  key:
    description: 'An explicit key for restoring and saving the cache'
    required: true
  restore-keys:
    description: 'An ordered list of keys to use for restoring the cache if no cache hit occurred for key'
    required: false
  nix_version:
    description: 'Nix version, defaults to `nixos-unstable`.'
    default: 'nixos-unstable'
  nix_file:
    description: 'Nix file, defaults to `default.nix`.'
    default: 'default.nix'
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
branding:
  icon: 'arrow-down'
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: ./dist/core.sh "prepare-restore"
    - id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          "/nix/store/"
          "/nix/var/nix/profiles/per-user/$USER/profile/bin/"
          "/nix/var/nix/profiles/default/bin/"
          "/nix/var/nix/profiles/per-user/root/channels/"
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
    - shell: bash
      run: echo "cache-hit=${{ steps.cache-restore.outputs.cache-hit }}" >> $GITHUB_OUTPUT
    - shell: bash
      run: |
        if [ "${{ steps.cache-restore.outputs.cache-hit" = "true" ]; then
          ./dist/core.sh "install-from-cache"
        else
          ./dist/core.sh "install-with-nix"
          ./dist/core.sh "prepare-save"
        fi
    - uses: actions/cache/save@v3
      with:
        path: |
          "/nix/store/"
          "/nix/var/nix/profiles/per-user/$USER/profile/bin/"
          "/nix/var/nix/profiles/default/bin/"
          "/nix/var/nix/profiles/per-user/root/channels/"
        key: ${{ inputs.key }}
